//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceInfo
    {
        public int DeviceID { get; set; }
        public int DeviceNO { get; set; }
        public string IPAddress { get; set; }
        public int PortNO { get; set; }
        public int BranchID { get; set; }
        public int FloorNO { get; set; }
    }
}
