//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Appointments1 = new HashSet<Appointment>();
            this.MeetingParticipants = new HashSet<MeetingParticipant>();
            this.MeetingRoomRequisitions = new HashSet<MeetingRoomRequisition>();
            this.MeetingRoomRequisitions1 = new HashSet<MeetingRoomRequisition>();
            this.PasswordCores = new HashSet<PasswordCore>();
            this.SEC_UserActionMapping = new HashSet<SEC_UserActionMapping>();
            this.SEC_UserGroup = new HashSet<SEC_UserGroup>();
            this.SEC_UserInformation = new HashSet<SEC_UserInformation>();
        }
    
        public int EmployeeID { get; set; }
        public Nullable<int> OnBehalfEmployeeID { get; set; }
        public int BranchID { get; set; }
        public int DepartmentID { get; set; }
        public int DesignationID { get; set; }
        public string Location { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string Mobile { get; set; }
        public string PbxNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> Floor { get; set; }
        public int CompanyID { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments1 { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual SET_CompanyBranch SET_CompanyBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingParticipant> MeetingParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingRoomRequisition> MeetingRoomRequisitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingRoomRequisition> MeetingRoomRequisitions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PasswordCore> PasswordCores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_UserActionMapping> SEC_UserActionMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_UserGroup> SEC_UserGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_UserInformation> SEC_UserInformation { get; set; }
    }
}
