//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeetingRoom()
        {
            this.MeetingRoomRequisitions = new HashSet<MeetingRoomRequisition>();
        }
    
        public int MeetingRoomID { get; set; }
        public string RoomNo { get; set; }
        public string FloorLocation { get; set; }
        public Nullable<int> SeatCapacity { get; set; }
        public string ProjectorAvailable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingRoomRequisition> MeetingRoomRequisitions { get; set; }
    }
}
