//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_UserInformation
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int CompanyID { get; set; }
        public int BranchID { get; set; }
        public string UserFullName { get; set; }
        public string UserName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public System.Guid PasswordID { get; set; }
        public System.Guid SecurityQuestionID { get; set; }
        public Nullable<bool> IsEMailVerified { get; set; }
        public Nullable<bool> IsPhoneNoVerified { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> UserGroupID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SEC_Password SEC_Password { get; set; }
        public virtual SEC_UserGroup SEC_UserGroup { get; set; }
    }
}
