//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_UIPage
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string UIPageName { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> UrlID { get; set; }
    
        public virtual SEC_UIModule SEC_UIModule { get; set; }
    }
}
