//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SET_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SET_Company()
        {
            this.SET_CompanyBranch = new HashSet<SET_CompanyBranch>();
        }
    
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string NameBN { get; set; }
        public string ShortName { get; set; }
        public string Code { get; set; }
        public string TaxNo { get; set; }
        public string RegistrationNo { get; set; }
        public string ContactNo { get; set; }
        public string EmailID { get; set; }
        public string Address { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SET_CompanyBranch> SET_CompanyBranch { get; set; }
    }
}
