//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SET_CompanyBranch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SET_CompanyBranch()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int BranchID { get; set; }
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string NameBN { get; set; }
        public string Code { get; set; }
        public string ContactNO { get; set; }
        public string Email { get; set; }
        public int IsHeadOffice { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public Nullable<int> HierarchyValue { get; set; }
        public int NoOfFloor { get; set; }
        public int Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual SET_Company SET_Company { get; set; }
    }
}
