//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTab
    {
        public int UserIndex { get; set; }
        public int PasswordId { get; set; }
        public int UserGroupId { get; set; }
    
        public virtual PasswordCore PasswordCore { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
